# Generated by Django 4.2.5 on 2023-10-10 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("todoapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="TodoListItem",
            new_name="todoapp_TodoListItem",
        ),
    ]
