# Generated by Django 4.2.1 on 2023-09-22 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backupapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="backup",
            name="request_d",
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="backup",
            name="system_name",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
