# Generated by Django 4.2.5 on 2023-10-04 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backupapp", "0002_backup_request_d_backup_system_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="backup",
            name="backup_type",
            field=models.TextField(default="04.10.2023"),
            preserve_default=False,
        ),
    ]
